### ISSUE TITLE
USER STORY: Initial Setup (Django)

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#1]
As a **developer** I can **setup the new project** so that **so that the project has its main structure/tools**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I Setup the project
**Then** I can start creating the project

## Tasks

- [x] **Task 1 -** Install Django
- [x] **Task 2 -** Create and env.py file to store all secret keys that will have
- [x] **Task 3 -** Make sure that env.py is in the .gitignore list, if it isn't, it must be added
