### ISSUE TITLE
USER STORY: Add product

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#10]
As an **Admin** I can **add a new product** so that **Users are able to buy**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I can click Add new product
**Then** I can be taken to add product page

## Tasks

- [x] **Task 1 -** Setup add product page
- [x] **Task 2 -** Create add product button
- [x] **Task 3 -** Check if is the Admin logged in
- [x] **Task 4 -** Confirmation of the new product added
