### ISSUE TITLE
USER STORY: Pagination

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#11]
As an **User** I can **go to the next or previous page** so that **I browse through an organized list of products**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that there are more then 6 products
**Then** a pagination system is in place

- **Acceptance Criteria 2**
**Given** that I have clicked NEXT page
**Then** I am taken to the next page where I can visualize the rest of products

## Tasks

- [x] **Task 1 -** Setup a pagination system to All products sections
- [x] **Task 2 -** Max of six products per page
- [x] **Task 3 -** Next and Previous page buttons
