### ISSUE TITLE
USER STORY: Edit a product

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#12]
As an **Admin** I can **edit a product** so that **the product info is updated**

## Acceptance Criteria

- Only Admin can edit a product
- Be able to update picture and info of the product

## Tasks

- [x] **Task 1 -** Create an edit product page
- [x] **Task 2 -** Add edit product link to the product
- [x] **Task 3 -** Create an edit product form
- [x] **Task 4 -** Add edit product notification
- [x] **Task 5 -** Check for Admin authentication
