### ISSUE TITLE
USER STORY: Delete product

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#13]
As an **Admin** I can **delete a product** so that **the customer does buy it if it doesn't exist**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I am the Admin
**Then** I can view delete option

- **Acceptance Criteria 2**
**Given** that I am in the delete confirmation page
**Then** I can click delete product

## Tasks

- [x] **Task 1 -** Create a delete product page
- [x] **Task 2 -** Create a delete form
- [x] **Task 3 -** Add a delete button link to the product
- [x] **Task 4 -** Notification at the end of deleting the product
