### ISSUE TITLE
USER STORY: Display all products

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#14]
As an **User** I can **access all products section** so that **I can view every product from the store**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I can access all products section
**Then** I can visualize all products

- **Acceptance Criteria 2**
**Given** that I can click on a product
**Then** I can view more details about the product

## Tasks

- [x] **Task 1 -** Create a template for all products
- [x] **Task 2 -** Create a view to display all products from the store
- [x] **Task 3 -** Create an all products link in the nav bar
- [x] **Task 4 -** Create a product model to display title, brand, picture and price
