### ISSUE TITLE
USER STORY: Product view

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#15]
As an **User** I can **view a single product** so that **I can view more detailed information and specifications**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I can click on the product
**Then** I can view all the details of the product

- **Acceptance Criteria 2**
**Given** that I want the product and click add
**Then** the product is added to the basket

## Tasks

- [x] **Task 1 -** Create a product view page
- [x] **Task 2 -** Create a link between the product and product view
- [x] **Task 3 -** Create a display view of the product
- [x] **Task 4 -** Add a back button so user can go back to the product list
- [x] **Task 5 -** Add a add to basket button so user can add the wanted product to the basket
- [x] **Task 6 -** If Admin is authenticated to display edit and delete buttons
