### ISSUE TITLE
USER STORY: Search product bar

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#16]
As an **User** I can **search** so that **I can find a specific product**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I have a search bar in products
**Then** I can type the wanted product

- **Acceptance Criteria 2**
**Given** that I have the results of my search
**Then** I can click on the wanted product

## Tasks

- [x] **Task 1 -** Add a search bar in products template
- [x] **Task 2 -** Add a view to retrieve and display all the products found from the query
- [x] **Task 3 -** Add notifications for the query
