### ISSUE TITLE
USER STORY: Products category

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#17]
As an **User** I can **filter the products** so that **only displays the selected product category**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I am in the products page
**Then** I can select the category

- **Acceptance Criteria 2**
**Given** that I selected a category
**Then** only the products from the selected category are displayed

## Tasks

- [x] **Task 1 -** Create a product category model
- [x] **Task 2 -** Database with different categories
- [x] **Task 3 -** Add a view to display only the products from the selected category
- [x] **Task 4 -** Create a drop down menu in the nav bar to select the wanted category
