### ISSUE TITLE
USER STORY: Product quantity

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#19]
As an **User** I can **adjust the quantity of the product** so that **I purchase the right amount**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I am in the basket
**Then** I can see the minus (-) and plus (+) buttons 

- **Acceptance Criteria 2**
**Given** that I can see the buttons to change quantity
**Then** I adjust the amount required

## Tasks

- [x] **Task 1 -** Add the minus and plus buttons
- [x] **Task 2 -** Implement the functionality
- [x] **Task 3 -** Quantity range from 1 to 99
- [x] **Task 4 -** Making sure that it does not go into minus when decreasing quantity
