### ISSUE TITLE
USER STORY: Remove Product from basket

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#20]
As an **User** I can **remove a product form the basket that I don't need** so that **I don't purchase it**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I am in the basket
**Then** I can see the remove product button

- **Acceptance Criteria 2**
**Given** that I have a product in the basket
**Then** I can remove it

- **Acceptance Criteria 3**
**Given** that I have removed the product
**Then** I can update the total

## Tasks

- [x] **Task 1 -** Add remove button to each product in the basket template
- [x] **Task 2 -** Add update button so that the user can update the new total after removing an item
- [x] **Task 3 -** Create the functionality to remove the product from basket
