### ISSUE TITLE
USER STORY: Stripe Setup

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#21]
As a **developer** I can **add stripe to the website** so that **the users can safely use their cards to purchase the products**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that the User enters a valid card credentials
**Then** the User should get a Confirmation of the order

- **Acceptance Criteria 2**
**Given** that the User enters invalid card credentials
**Then** the User should get an error message letting him/her know that something went wrong

- **Acceptance Criteria 3**
**Given** that the User is logged in and all details have been saved from previous orders
**Then** all delivering information should automatically display

## Tasks

- [x] **Task 1 -** Create a checkout template
- [x] **Task 2 -** Sign up and setup Stripe in order to be able to get the API keys to run the purchasing process
- [x] **Task 3 -** Add all the required settings into the project settings
- [x] **Task 4 -** Add the keys to the env.py and heroku app, make sure that env.py is in .gitignore
- [x] **Task 5 -** Create an Order confirmation page to display the order details
