### ISSUE TITLE
USER STORY: Admin dashboard

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#24]
As an **Admin** I can **access to the website dashboard** so that **I can manage the website**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I am the Admin
**Then** I can access the website dashboard

- **Acceptance Criteria 2**
**Given** that I am the Admin and I am in the website dashboard
**Then** manage the website

- **Acceptance Criteria 2**
**Given** that I am the Admin and I am in the website dashboard
**Then** manage the users

## Tasks

- [x] **Task 1 -** Create an Admin dashboard
- [x] **Task 2 -** Check for Admin authentication only for access
- [x] **Task 3 -** Organize the dashboard, Users, Products, orders
- [x] **Task 4 -** Manage Users of the website
