### ISSUE TITLE
USER STORY: Admin dashboard add products

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#25]
As an **Admin** I can **add products from the website dashboard** so that **the users have more offers to buy**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I log in to the admin dashboard
**Then** I can go to products section

- **Acceptance Criteria 2**
**Given** that I am in products section
**Then** I can add a new product to the website

## Tasks

- [x] **Task 1 -** Create add product page in admin dashboard
- [x] **Task 2 -** Create a form with the respective details fields for the product
- [x] **Task 3 -** Create the functionality to add the products
- [x] **Task 4 -** Successful notification once the product is added to the website
