### ISSUE TITLE
USER STORY: Admin dashboard delete product

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#26]
As an **Admin** I can **delete a product from the website** so that **the user doesn't buy it if no longer available**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I log in  to the admin dashboard
**Then** I can go to the product section

- **Acceptance Criteria 2**
**Given** that I have selected the product
**Then** I can delete it

- **Acceptance Criteria 3**
**Given** that I have deleted the product
**Then** I get a notification

## Tasks

- [x] **Task 1 -** Add delete product to the product dashboard
- [x] **Task 2 -** Choose from a list of products and select the product
- [x] **Task 3 -** Create the functionality to delete the product
- [x] **Task 4 -** Successful notification once the product is deleted from the website
