### ISSUE TITLE
USER STORY: Admin dashboard edit product

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#27]
As an **Admin** I can **update the product details** so that **the user sees it with correct details/info**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I log in to the admin dashboard
**Then** I can go to products section

- **Acceptance Criteria 2**
**Given** that I select the product from the list of products
**Then** I can click edit the product

## Tasks

- [x] **Task 1 -** Create edit product page in admin dashboard
- [x] **Task 2 -** Create a form with the respective details fields for the product to be edit
- [x] **Task 3 -** Create the functionality to edit the products
- [x] **Task 4 -** Successful notification once the product is edited
