### ISSUE TITLE
USER STORY: Delete review

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#30]
As an **User** I can **delete the review that I left in the product** so that **the product no longer has my review**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I have left the review 
**Then** I can delete it

## Tasks

- [x] **Task 1 -** Create a delete review template
- [x] **Task 2 -** Create a functionality to delete
- [x] **Task 3 -** Notification of the deleted review
