### ISSUE TITLE
USER STORY: Edit review

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#31]
As an **User** I can **edit my review** so that **the users can read the updated review**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I wrote the review
**Then** I can edit it

## Tasks

- [x] **Task 1 -** Create an edit review template
- [x] **Task 2 -** Create a functionality to edit the review
- [x] **Task 3 -** Notification of the review edited
