### ISSUE TITLE
USER STORY: Newsletter subscription

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#32]
As an **User** I can **subscribe** so that **I can get the latest offers**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I have subscribed
**Then** I get a message confirming it

## Tasks

- [x] **Task 1 -** Create a Mailchimp account
- [x] **Task 2 -** Add the code provided by Mailchimp onto the website footer
- [x] **Task 3 -** Test to see if it works correctly, type the email and check the Mailchimp database
