### ISSUE TITLE
USER STORY: Search Engine Optimization (SEO)

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#33]
As an **Admin/Owner** I can **improve the website SEO** so that **the website gets ranked higher to attract customers**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I am the admin/owner of the website 
**Then** I can make sure that the title and meta tags are relevant  

## Tasks

- [x] **Task 1 -** Improve the meta tags
- [x] **Task 2 -** Convert the image files to improve the website rendering/loading speeds
- [x] **Task 3 -** Create a sitemap.xml and robots.txt files to improve the search engine and indexing of the website pages
- [x] **Task 4 -** To all external links through the website add rel="noopener nofollow"
