### ISSUE TITLE
USER STORY: Contact

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#35]
As an **User** I can **contact the website** so that **I get the right support**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I need to contact the TopTech support
**Then** I can see contact link in the navbar

- **Acceptance Criteria 2**
**Given** that I click contact
**Then** I am presented with a contact form

## Tasks

- [x] **Task 1 -** Create a contact form template
- [x] **Task 2 -** Create a contact form 
- [x] **Task 3 -** Create a contact form functionality
- [x] **Task 4 -** Display a notification after submitting the form
