### ISSUE TITLE
USER STORY: Document all tests

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#36]
## Tasks

- [x] **Task 1 -** Run all code validation tests
- [x] **Task 2 -** Lighthouse tests
- [x] **Task 3 -** Test the website in different browsers and devices
- [x] **Task 4 -** The website responsiveness
