### ISSUE TITLE
USER STORY: About Us

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#38]
As an **User** I can **visit the About page** so that **I get to know more about the company such as history or opening times**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I have About Us link in the navbar
**Then** I can click to access it

- **Acceptance Criteria 2**
**Given** that I have About page opened
**Then** I can check the company details such as opening times
## Tasks

- [x] **Task 1 -** Create an About app
- [x] **Task 2 -** Create an About template
- [x] **Task 2 -** Create an About view to display the content to the Users
