### ISSUE TITLE
USER STORY: Edit About Us

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#39]
As an **Admin** I can **Edit/update the about page** so that **the company information is always updated for the Users**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** I can click the Edit About link
**Then** I am taken to Edit about page

- **Acceptance Criteria 2**
**Given** I am in the edit about
**Then** I can start updating the information

## Tasks

- [x] **Task 1 -** Create an Edit about form
- [x] **Task 2 -** Create an Edit about view
- [x] **Task 3 -** Create an Edit about template
- [x] **Task 4 -** Display notification
