### ISSUE TITLE
USER STORY: Initial deployment

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#4]
As a **developer** I can **deploy before starting the project** so that **I can make sure that is all running before getting too deep in the development and having problems with deploying later and also to test it while developing**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that deployment is all done
**Then** I can carry on with the project and test it along the way

## Tasks

- [x] **Task 1 -** Create a Procfile and requirements.txt, make sure to commit and push
- [x] **Task 2 -** Create a new app in Heroku
- [x] **Task 3 -** Connect it to your github project and add all secret keys to config vars
- [x] **Task 4 -** Deploy and test to make sure is running properly
