### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#5]
As an **User** I can **register an account** so that **access/view my profile/orders**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I can access the registration from the nav bar 
**Then** I can click and start registering

- **Acceptance Criteria 2**
**Given** that I have registered
**Then** I can confirm by using the link received in the email

## Tasks

- [x] **Task 1 -** Add Signup link to the nav bar
- [x] **Task 2 -** signup form should have email, username and password
- [x] **Task 3 -** Make sure that the same email or username cannot be registered twice. (Have to be unique)
- [x] **Task 4 -** Email confirmation prior to login
