### ISSUE TITLE
USER STORY: Log out

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#7]
As an **User** I can **logout** so that **my account is logged off**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that there is a logout link in the nav bar and I have clicked it
**Then** I am taken to a Logout confirmation page

- **Acceptance Criteria 2**
**Given** that I have confirmed to log out
**Then** I am taken to the home page with a confirmation message

## Tasks

- [x] **Task 1 -** Add log out link to nav bar
- [x] **Task 2 -** Setup a log out page
- [x] **Task 3 -** Taken to home page and confirmation message
