### ISSUE TITLE
USER STORY: Delete account

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project5#9]
As an **User** I can **delete my account** so that **all my data is deleted**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I can delete my account
**Then** that my data/details are deleted

## Tasks

- [x] **Task 1 -** Setup a delete account page
- [x] **Task 2 -** Add delete button to profile page
- [x] **Task 3 -** Add confirmation notification
